# Generated by Django 4.0.3 on 2022-03-04 13:52
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PokedexCreature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("ref_number", models.PositiveSmallIntegerField()),
                ("generation", models.PositiveSmallIntegerField()),
                ("legendary", models.BooleanField(default=False)),
                ("type_1", models.CharField(max_length=20)),
                ("type_2", models.CharField(blank=True, max_length=20, null=True)),
                ("total", models.PositiveSmallIntegerField()),
                ("hp", models.PositiveSmallIntegerField()),
                ("attack", models.PositiveSmallIntegerField()),
                ("defense", models.PositiveSmallIntegerField()),
                ("special_attack", models.PositiveSmallIntegerField()),
                ("special_defence", models.PositiveSmallIntegerField()),
                ("speed", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
