# Generated by Django 3.2.12 on 2023-03-15 17:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0002_rename_surname_pokemon_nickname'),
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonPreferredObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100)),
                ('image', models.CharField(blank=True, max_length=200)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                'verbose_name_plural': "Pokemon Preferred object's",
                'ordering': ['name'],
            },
        ),
    ]
