# Generated by Django 3.2.12 on 2023-03-15 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pokemon', '0003_pokemonpreferredobject'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pokemon_object',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='pokemon.pokemonpreferredobject'),
        ),
    ]
