# Generated by Django 3.2.12 on 2023-03-17 20:59
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    dependencies = [
        ("pokemon", "0005_auto_20230317_1717"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pokemon",
            name="pokemon_team",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="pokemon.pokemonteam",
            ),
        ),
    ]
